### ISSUE TITLE
Tracking `next` release

### ISSUE THREAD

**Issue by STRML** [STRML/react-grid-layout#129]
As many have you been awaiting, the `next` branch:

* Contains a refactor of most of the project
* Has React 0.14 Support
* Has better IE/Touch compatibility
* Is fully validated using Flow
* Uses mainline React-Draggable and React-Resizable (1.x versions).

Much of the difficulty in this branch involves a rethinking of how we manage state in child components and a move toward a completely stateless `<Draggable>`, which is not yet integrated in RGL.

This issue is tracking the release of this branch. See also discussion in #117.

Blockers:

- [x] React-Draggable 1.x is calling back with clientX/Y when it should be sending offsetX/Y. This is causing a bad 300px offset in the demo. (fixed in https://github.com/mzabriskie/react-draggable/commit/c1a5bb3daaebfef07512fabf9dfbd435279241c8)
- [x] Draggable is not following mouse position with placeholder in the grid, it is instead following the placeholder directly. For example:
  -  **(Correct, old branch)** ![screen shot 2015-11-23 at 4 40 34 pm](https://cloud.githubusercontent.com/assets/1197375/11352269/09846b96-9201-11e5-8d77-07fe874ed111.jpg)
  - **(Incorrect, `next` branch)** ![screen shot 2015-11-23 at 4 40 55 pm](https://cloud.githubusercontent.com/assets/1197375/11352271/1489d76a-9201-11e5-9fd1-dd1012f04b8c.jpg) 
- [x] Use `<DraggableCore>` directly and store state in RGL, rather than in each `<Draggable>`.

Stretch goals:

- [ ] Once onto `<DraggableCore>`, we can use percentage top/left and height/width directly. This will not only allow us to stop listening for resize events, but do more proper server-side rendering.
  - Can we still use CSS transforms with percentages? CSS transform percentages are relative to the element's width/height, not the offsetParent's width/height. We could trick it by measuring the offsetParent and doing the math with JS, but we lose the server-rendering benefits as above.

**Comment by STRML** [comment]
Paging @aweber1 and @benmosher, do you have any ideas on how to do CSS transforms with percents, or should we just drop it entirely and use top/left? If we end up hacking percentages into transforms by measuring the offsetParent, it seems we're back in the same boat of having to constantly measure the offsetParent to make sure we're getting it right.

**Comment by benmosher** [comment]
Since you know each cell is `w` columns wide, isn't the position x/w * 100%? Where `x` is the left position?

i.e. a 4-column cell at x-position 8 should be at 100 * 8/4 = 200%?

I'm not positive I understand percentage transforms correctly, but I think this would work.

**Comment by STRML** [comment]
Not sure if I follow, if it's 4-column, (available x-positions are `0` `1` `2` `3`), how would a cell be at position 8?

I get what you're at, though. If the cells themselves resize based on the width of the container, then the transform percentages should remain constant, so long as the margins are also percentage-based.

**Comment by benmosher** [comment]
Sorry, I was thinking a 4-wide cell in a 12-wide layout. So position 8 would be the furthest right position. But yeah, the transform will change whenever either the width of the position changes, but the math is easy enough, especially with React managing it.

**Comment by benmosher** [comment]
*width _or_ position

**Comment by STRML** [comment]
I've published `0.10.0-beta0` as a pre-release of the `next` branch.

**Comment by maitriyogin** [comment]
this is supremely cool! the offset problem is now gone ...
Although I can't seem to get resizing to work?
Obviously I'v set isResizable to true, although I don't get a resize chevron.
/Stephen.

**Comment by Puffton** [comment]
Will #87 also be fixed as part of this upgrade to React 0.14?

**Comment by maitriyogin** [comment]
Actualy, the weirdest thing is happening.  If I send in a layout and have a handler on onlayoutchange, after the initial render onlayoutchange is called with a mutated layout array with the widths and x locations set to 1... The us are stacked. This results in a list of grid items with a width of 1.
Why would the layout properties change like this?
/stephen

**Comment by mrblueblue** [comment]
@maitriyogin, resizing initially didn't work for me too, but I found that it was just a CSS issue.

In the newer implementation of `react-resizable`, I'm only seeing the `react-resizable-handle` class applied to the span:

```html
<div className='react-grid-item...' >
  <DraggableCore>
    <span className='react-resizable-handle' />
  </DraggableCore>
</div>

```

whereas the old implementation had the `react-draggable` class applied to it as well.

```html
<span className='react-resizable-handle react-draggable' />
```

So, I had to just modify my existing css by removing `react-draggable` in the selector:

``` css
.react-resizable-handle {
  position: absolute;
  width: 20px;
  height: 20px;
  bottom: 0;
  right: 0;
  background: url('data:image/svg+xml...)
  background-position: bottom right;
  padding: 0 3px 3px 0;
  background-repeat: no-repeat;
  background-origin: content-box;
  box-sizing: border-box;
  cursor: se-resize;
}
```

**Comment by MarcBalaban** [comment]
@mrblueblue :+1:

**Comment by maitriyogin** [comment]
I worked out why the layout props where being reset ... It's because the id 'i' has changed to only allow an int (`synchronizeLayoutWithChildren getLayoutItem`).  Before it could be a string.
I'v changed to int id's and everything's fine and dandy.
/Stephen.

**Comment by maitriyogin** [comment]
Hiya, sorry for being a pain but have noticed that individual layout's aren't working.
The child.key isn't getting intified on line starting at 374 utils.js : 
``` 
if (verticalCompact) {
        layout.push((0, _objectAssign2['default'])({}, g, { y: Math.min(bottom(layout), g.y), i: child.key }));
      } else {
        layout.push((0, _objectAssign2['default'])({}, g, { y: g.y, i: child.key }));
      }
```

child.key should be parseInt(child.key)

**Comment by maitriyogin** [comment]
Hiya,
Just a quick not about safari, in that it's a bit jumpy when dragging and resizing.
Is this a css thing?
Cheers,
/stephen

**Comment by Puffton** [comment]
Why are the children id's forced to be ints now? It's a breaking change for me, so I was just wondering if there was a good reason.

**Comment by STRML** [comment]
That wasn't intentional and was backed out in https://github.com/STRML/react-grid-layout/commit/b4bb88d002ce2c855be20dc212c868711099f1c7

**Comment by maitriyogin** [comment]
Hiya, just wondering if you'v noticed that dragging in safari is pretty shaky or jumpy?
I'v pulled the next branch, built and am running npm run dev.
When I view any of the examples or even first dev page I get a very jumpy drag in safari.
In the current release for react 0.13 it's great! very smooth.
Any ideas?
/Stephen.

**Comment by maitriyogin** [comment]
hmm seems to be csstransforms ? if this is enabled I get a jittery drag .
/Stephen.

**Comment by zhaozhiming** [comment]
Hi, when will this version to release?

**Comment by dmr** [comment]
What can I do to help with the next release? What is missing from the initial goals?

**Comment by STRML** [comment]
It's almost there but has some CSS bugs, most notably with the pink placeholder div.

Once those are cleared up and it's at parity with the old release, it can be tagged and published.

I'm considering moving to a completely percentage-based layout, but that doesn't have to be in `0.10`. `0.10` fixes some critical interop issues with old IE et al so I'd rather just get it out the door.

**Comment by dmr** [comment]
Thank you for the quick response, good to hear that a release will come soon :)

**Comment by nvarchar** [comment]
I'm trying to install the next branch with `npm`, but the ./build directory isn't getting included in node_modules/react-grid-layout. When I install the master branch, it works fine. This is the command I'm using.

`npm install --save https://github.com/STRML/react-grid-layout.git#next`

**Comment by tobias-kuendig** [comment]
You have to use the tagged beta Release 0.10. 0-beta1

Paul Karpenko <notifications@github.com> schrieb am Mo., 18. Jan. 2016,
21:46:

**Comment by menelike** [comment]
I'm not sure about this one. If React is built as an external source in the webpack.config, shouldn't  ReactDOM be treated the same way?

**Comment by nvarchar** [comment]
@tobias-kuendig This worked great, thank you!

**Comment by maitriyogin** [comment]
Hi, I'm having trouble with csstransforms in safari, works great in chrome. Symptoms : Dragging and resizing are very jumpy in safari. 
Works ok if I turn off csstransforms.
Maybe I'm missing some Css?
/Stephen

**Comment by maitriyogin** [comment]
Hi,I'v really been digging into this, mainly by putting logging in the render function of GridItem.
My hunch was that the pos, left was jumping. 
On logging these values as well as the computed style (createStyle) are smooth and consistent.
I was hoping to see that say a left when snapping to a new grid position would toggle back to the old value, so something like : 
// drag to left 
render ---
old left   : 50
new left : 10
render --- // jump to new left grid 
old left   : 10
new left : 50  < -- toggles back and causes the jump ...

Unfortunately or fortunately it doesn't do this ... which is kind of frustrating.
Instead I get what is expected although a jittery safari:

render ---
old left   : 50
new left : 10
render --- // jump to new left grid 
old left   : 10
new left : 10
render --- // still on last jump as mouse hasn't moved enough for a grid snap
old left   : 10
new left : 10

My only conclusion is that safari just doesn't like the sudden jump of translate... sometimes .. and gets jittery..

I'v gone back to useCssTransforms = false, although if any one else has this issue I sure would like some help ...
Cheers,
Stephen.

**Comment by STRML** [comment]
Holy cow, we released it! Thanks @menelike for all your help.

You can now install `0.10.1` from npm.

**Comment by mosse** [comment]
Fantastic stuff! Thanks so much @STRML :)

**Comment by maitriyogin** [comment]
cool!
Have you guys noticed that Amazon Web Services are using react-grid-layout in their Cloud watch dashboard ?
/Stephen.

**Comment by menelike** [comment]
@STRML And we dropped the dist size from 173KB to 61.8KB. Especially due to much cleaner externalization of ReactDOM.

But there also some breaking changes, docs and examples need to be updated. I made a PR issuing this a few minutes ago.

**Comment by STRML** [comment]
> Have you guys noticed that Amazon Web Services are using react-grid-layout in their Cloud watch dashboard ?

:heart_eyes: Wow!
